### ISSUE TITLE
Doesn't work on Ipad 

### ISSUE THREAD

**Issue by JerryBels** [dpa99c/phonegap-istablet#10]
**I'm submitting a ...**  (check one with "x"):
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Doesn't detect that an ipad is a tablet. Ran on an Ipad pro 10.5'' emulator.

**Expected behavior:**

Should detect that an Ipad is a tablet.

**Steps to reproduce:**

On deviceReady event, run : 

```
    const isTablet = (window as any).isTablet;
    console.log("ISTABLET : ", isTablet);
```

**Environment information**

```
$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

And thanks for your great work :)

**Comment by dpa99c** [comment]
Seems to work fine running the [example project](https://github.com/dpa99c/phonegap-istablet-example) on iPad Pro 10.5" Simulator:

![Screenshot 2019-07-19 at 13 26 54](https://user-images.githubusercontent.com/2345062/61535050-2608c200-aa29-11e9-8343-705972993eaf.png)

As you can see from the Xcode breakpoint, the [`UI_USER_INTERFACE_IDIOM` is correctly determined as `UIUserInterfaceIdiomPad`](https://github.com/dpa99c/phonegap-istablet/blob/master/src/ios/IsTablet.m#L36)

**Comment by JerryBels** [comment]
Okay, strange, I will have to investigate more I guess... Thanks you for taking the time to look into it, will report if something relevant comes up.
