### ISSUE TITLE
Not working on emulators

### ISSUE THREAD

**Issue by dasomen** [dpa99c/phonegap-istablet#2]
Hello,

I was wondering if there is something wrong with the plugin since detetction on neither Android's SDK emulator nor Gentrymotion's emulator detect the device as a tablet.

For instance I'm using the Custom Tablet - 5.0.0 - API 21 - 2560x1600 virtual device on Genymotion, yet the plugin says it is NOT a tablet.

Could you please advice?

Thanks in advance.

Attached Image, both virtual devices result in a 'NOT' tablet respose:
![capture](https://cloud.githubusercontent.com/assets/1049313/10232643/92d56a70-684f-11e5-9f33-78f7ef265ea9.JPG)

**Comment by dpa99c** [comment]
Just tested the [example project](https://github.com/dpa99c/phonegap-istablet-example) on one of the emulators mentioned above and it works fine - reports the device is a tablet - see screen capture video here: [http://ge.tt/api/1/files/1K3DO5P2/0/blob?download](http://ge.tt/api/1/files/1K3DO5P2/0/blob?download)

Can you clone and test the example project to confirm whether or not it works for you?

**Comment by dasomen** [comment]
Hello, you're absolutelly right! the example project works well.

Seems the problem is I was using window.isTablet outside of the onDeviceReady function.

Thank you very much for the fast response and the amazing plugin.
