### ISSUE TITLE
windows phone support

### ISSUE THREAD

**Issue by doradsoft** [dpa99c/phonegap-istablet#4]
Could you add support for detecting windows phone tablets too?

Thanks

**Comment by dpa99c** [comment]
will have a look when I get time

**Comment by dpa99c** [comment]
Given that Windows Phone/Mobile market share is [now below 0.3%](https://adtmag.com/articles/2017/02/16/windows-mobile.aspx), this is just not worth the effort.

**Comment by dpa99c** [comment]
Lucky day: [pull request by timonorawski](https://github.com/dpa99c/phonegap-istablet/pull/7) adds Windows support.

Published to npm as v1.2.0

Maybe I should close issues as `wontfix` more often :-)
