### ISSUE TITLE
npm @types

### ISSUE THREAD

**Issue by tomgallagher** [dpa99c/phonegap-istablet#5]
Hi

Great plugin - saved me a lot of time.

Any chance you could add your typings to npm @types as other cordova plugins have done?

Would be helpful for those of us using typescript.

Thanks

Tom

**Comment by dpa99c** [comment]
I don't see that any cordova plugins have added typings to the @types repo: [https://github.com/types?utf8=%E2%9C%93&query=cordova](https://github.com/types?utf8=%E2%9C%93&query=cordova)

A select number of plugins (including 2 of my own) have been selected for inclusion in [Ionic Native](https://ionicframework.com/docs/v2/native/) and have therefore had [typescript wrappers](https://github.com/driftyco/ionic-native/tree/master/src/plugins) defined by the Ionic team.

**Comment by tomgallagher** [comment]
Hi there

https://www.npmjs.com/search?q=%40types+cordova+plugin

That's where I found the ones for the network information cordova plugins.

I actually sidestepped the problem by using 

`window['isTablet']`

in Typescript but I thought I'd mention it anyway.

Which plugins do you have in Ionic Native? I'm impressed.

**Comment by dpa99c** [comment]
Ah, OK, now I found the definitions - they are here: [https://github.com/DefinitelyTyped/DefinitelyTyped/pulls](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls)

I'll add a pull request with definitions for this plugin (and my others) and link it here.

My plugins in Ionic Native are [Diagnostic](https://ionicframework.com/docs/v2/native/diagnostic/) and [Launch Navigator](https://ionicframework.com/docs/v2/native/Launch%20Navigator/)

**Comment by dpa99c** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11986](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11986)
